// This snippet file was generated by processing the source file:
// ./messaging-next/service-worker.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_init_in_sw_modular]
import { initializeApp } from "firebase/app";
import { getMessaging } from "firebase/messaging/sw";

// Initialize the Firebase app in the service worker by passing in
// your app's Firebase config object.
// https://firebase.google.com/docs/web/setup#config-object
const firebaseConfig = {
  apiKey: "AIzaSyDP5jy66Zlhq1ZgP5i63rYftxmsV_j6SaM",
  authDomain: "ticket-9dd8c.firebaseapp.com",
  projectId: "ticket-9dd8c",
  storageBucket: "ticket-9dd8c.appspot.com",
  messagingSenderId: "91734333449",
  appId: "1:91734333449:web:357db34d1cc6ea05b200d8",
  measurementId: "G-YF8C66GRG2"
};

// Retrieve an instance of Firebase Messaging so that it can handle background
// messages.
const messaging = getMessaging(firebaseApp);